In [1]:
import pandas as pd
import numpy as np
from pandas import  Series, DataFrame

In [2]:
# 산술 연산과 데이터 정렬
s1 = pd.Series ([7.3, -2.5, 3.4, 1.5], index = ['a', 'c', 'd', 'e'])
s2 = pd.Series ([-2.1, 3.6, -1.5, 4, 3.1],
               index = ['a', 'c', 'e', 'f', 'g'])

In [3]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [4]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [5]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [11]:
import numpy as np
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns = list('bcd'),
                  index = ['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns = list('bde'),
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [12]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [13]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [14]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [15]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
df1

A
0  1
1  2

In [16]:
df2

B
0  3
1  4

In [17]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [18]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                  columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                  columns = list('abcde'))
df2.loc[1, 'b'] = np.nan
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [19]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [20]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [21]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [22]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [23]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [24]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [25]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [26]:
arr[0]

array([0., 1., 2., 3.])

In [27]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [29]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns = list('bde'),
                    index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [30]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [31]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [32]:
series2 = pd.Series(range(3), index = ['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [33]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [34]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [35]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [36]:
frame.sub(series3, axis = 'index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [37]:
frame = pd.DataFrame(np.random.randn(4, 3), columns = list('bde'),
                    index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    0.426796  0.081178 -0.117448
Ohio   -1.760336 -0.852106  0.265695
Texas   1.052035  0.911261  0.922832
Oregon -1.007320 -1.418923 -2.765147

In [38]:
np.abs(frame)

b         d         e
Utah    0.426796  0.081178  0.117448
Ohio    1.760336  0.852106  0.265695
Texas   1.052035  0.911261  0.922832
Oregon  1.007320  1.418923  2.765147

In [39]:
# 함수 적용
# map, apply, applymap 비교
df = pd.DataFrame({'a': [1, 2, 3, 4], 'b': [9, 10, 11, 12]})
df

a   b
0  1   9
1  2  10
2  3  11
3  4  12

In [40]:
# map 함수
f1 = lambda x : "%03d"%x
list(map(f1, df['b']))

['009', '010', '011', '012']

In [41]:
# map, apply, applymap 비교
df = pd.DataFrame({'a': [1, 2, 3, 4], 'b': [5, 6, 7, 8], 'c': [9, 10, 11, 12]})
df

a  b   c
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [42]:
# map 함수
f1 = lambda x : "%03d"%x
df['b'].map(f1)

0    005
1    006
2    007
3    008
Name: b, dtype: object

In [43]:
# apply 메서드
f2 = lambda x:x.max()-x.min()
df.apply(f2)

a    3
b    3
c    3
dtype: int64

In [44]:
df.apply(f2, axis = 1)

0    8
1    8
2    8
3    8
dtype: int64

In [45]:
df.apply(sum, 1)

0    15
1    18
2    21
3    24
dtype: int64

In [46]:
round(df.apply(np.mean, 1), 2)

0    5.0
1    6.0
2    7.0
3    8.0
dtype: float64

In [47]:
# 함수 적용과 매핑
frame = pd.DataFrame(np.random.randn(4, 3), columns = list('bde'),
                    index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.120411 -0.364817 -0.580559
Ohio    0.046688  0.864570  3.221121
Texas  -1.137364 -0.567300 -0.920425
Oregon -0.052616 -0.652706 -2.359075

In [48]:
f = lambda x:x.max() - x.min()
frame.apply(f)

b    1.184052
d    1.517276
e    5.580195
dtype: float64

In [49]:
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])
frame.apply(f)

b         d         e
min -1.137364 -0.652706 -2.359075
max  0.046688  0.864570  3.221121

In [50]:
# applymap 메서드
df

a  b   c
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [52]:
f4 = lambda x:x * 10
df.applymap(f4)

a   b    c
0  10  50   90
1  20  60  100
2  30  70  110
3  40  80  120

In [53]:
obj = pd.Series(range(4), index = ['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [54]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [56]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index = ['three', 'one'],
                    columns = ['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [57]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [58]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [59]:
frame.sort_index(axis = 1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [60]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [61]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [62]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [64]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [65]:
frame = pd.DataFrame({'b' : [4, 7, -3, 2], 'a' : [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [66]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [67]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [68]:
# 데이터 순위
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [69]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [70]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [71]:
obj.rank(ascending = False, method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [72]:
frame = pd.DataFrame({'b' : [4.3, 7, -3, 2], 'a' : [0, 1, 0, 1],
                     'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [74]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [75]:
frame.rank(axis = 'rows')

b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

In [76]:
# 중복 색인
obj = pd.Series(range(5), index = ['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [77]:
obj.index.is_unique

False

In [78]:
obj['a']

a    0
a    1
dtype: int64

In [79]:
obj['c']

4

In [82]:
df = pd.DataFrame(np.random.randn(4, 3), index = ['a','a','b','b'])
df

0         1         2
a  0.964854 -1.651111  1.126606
a  0.029608  0.122924  0.311435
b  0.149110 -0.467047 -0.992270
b  1.595782 -0.522981  1.335413

In [83]:
df.loc['b']

0         1         2
b  0.149110 -0.467047 -0.992270
b  1.595782 -0.522981  1.335413

In [84]:
# 기술 통계 / 요약 통계
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                 [np.nan, np.nan], [0.75, -1.3]],
                 index = ['a', 'b', 'c', 'd'],
                 columns = ['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [85]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [86]:
df.sum(axis = 'columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64